title: EVCS Analytics
description: Data Science and Experimentation in a growing EV Charging network
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
